name: pushDocs

on:
  push:
    branches: 
     - master


jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@main

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@main
        with:
          node-version:  ${{ matrix.node }}
      
      - name: Install dependencies
        run: yarn install
    
      - name: Build VuePress
        run: yarn build
      
      - name: Deploy to Pages
        run: |
          cd .vitepress/dist 
          git init
          git config user.name "gelxgx"
          git config user.email "${{ secrets.GIT_EMAIL }}"
          git add -A
          git commit -m 'deploy'
          git push -f https://Lgweon:${{ secrets.TOKEN }}@github.com/Lgowen/blog.git master:gh-pages
          cd -
